language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm-nightly

before_script:
  - curl https://phar.phpunit.de/phpunit-alpha.phar > phpunit && chmod +x phpunit
  - composer self-update
  - composer require satooshi/php-coveralls:dev-master --no-update --dev
  - composer install --dev --prefer-source

script:
    - ./phpunit

after_script:
  - php vendor/bin/coveralls
